#To Edit   https://editor.swagger.io/
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/member-data":
    get:
      summary: JWT implementation was correct or not
      security:
        - BearerAuth: []
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          description: No verification key available
  "/users/sign_in":
    post:
      summary: create session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  required: true
                  properties:
                    email:
                      type: string
                    password:
                      type: string
              example:
                user:
                  email: testing@testing.com
                  password: fnjandsdf25341f35s
      responses:
        "200":
          description: successful
        "401":
          description: Invalid Email or password.
          content:
            text/plain:
              schema:
                type: string
                example: Invalid Email or password.
  "/users/sign_out":
    delete:
      summary: delete session
      security:
        - BearerAuth: []
      responses:
        "200":
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: You are logged out.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Hmm nothing happened.
  "/users/cancel":
    get:
      summary: cancel registration
      responses:
        "200":
          description: successful
  "/users/sign_up":
    get:
      summary: new registration
      responses:
        "200":
          description: successful
  "/users/edit":
    get:
      summary: edit registration
      responses:
        "200":
          description: successful
  "/users":
    patch:
      summary: update registration
      responses:
        "200":
          description: successful
    put:
      summary: update registration
      responses:
        "200":
          description: successful
    delete:
      summary: delete registration
      responses:
        "200":
          description: successful
    post:
      summary: create registration
      responses:
        "200":
          description: successful
servers:
  - url: http://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: localhost:3000
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
